# Generated by Django 5.2.6 on 2025-09-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=50, null=True)),
                ('Contact', models.CharField(max_length=20, null=True)),
                ('Age', models.IntegerField(null=True)),
                ('City', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('Subject', models.CharField(max_length=100, null=True)),
                ('Department', models.CharField(max_length=100, null=True)),
                ('City', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
