# Generated by Django 5.2.1 on 2025-09-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Price', models.IntegerField(null=True)),
                ('Category', models.CharField(null=True)),
                ('Department', models.CharField(max_length=100, null=True)),
                ('City', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
